name: SuperShallowDeepUConvKAN
goal: super_shallow_deep_u_conv_kan
shared: False
module:
  _target_: model.super_shallow_deep_u_conv_kan.SuperShallowDeepUConvKAN
  _recursive_: False
  channels: ${dataset.ms_channels}
  hidden_channels: 64
train:
  batch_size: 10
  num_workers: 16
  max_epochs: 250
loss:
  _target_: loss.DiceBCELoss

optimizer:
  _target_: torch.optim.Adam
  lr: 1.e-4
  betas:
    - 0.9
    - 0.999
  eps: 1.e-8
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones:
    - 1000
  gamma: 1