name: SwinUnet
goal: vision_transformer
shared: False
module:
  _target_: src.sota.Swin-Unet.networks.vision_transformer.SwinUnet
  _recursive_: False
  num_classes: 1
  img_size: 64
  config:
    MODEL:
      DROP_RATE: 0.0
      DROP_PATH_RATE: 0.1
      SWIN:
        PATCH_SIZE: 4
        IN_CHANS: 12
        EMBED_DIM: 96
        DEPTHS: [2, 2, 6, 2]
        NUM_HEADS: [12, 24, 48, 96]
        WINDOW_SIZE: 7
        MLP_RATIO: 4.
        QKV_BIAS: True
        QK_SCALE: None
        APE: False
        PATCH_NORM: True
        PRETRAIN_CKPT: False
    DATA:
      IMG_SIZE: 64
    TRAIN:
      USE_CHECKPOINT: False

train:
  batch_size: 100
  num_workers: 16
  max_epochs: 100
loss:
  _target_: loss.SwinLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 1.e-4
  betas:
    - 0.9
    - 0.999
  eps: 1.e-8
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones:
    - 1000
  gamma: 1