name: "UKAN"
goal: u_kan
shared: False
module:
  _target_: model.${model.goal}.${model.name}
  _recursive_: False
  channels: ${dataset.ms_channels}
  sampling: ${sampling}
  iter_stages: 3
train:
  batch_size: 32
  num_workers: 16
  max_epochs: 2000
loss:
  _target_: loss.DiceBCELoss

optimizer:
  _target_: torch.optim.Adam
  lr: 1.e-4
  betas:
    - 0.9
    - 0.999
  eps: 1.e-8
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones:
    - 1000
  gamma: 1