name: marida
ms_channels: 12
train:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.${dataset.name}.${dataset.name}
    root: ${oc.env:DATASET_PATH}/${dataset.name}
    fold: train
    seed: 42
    output_size: 64
    channels: ${dataset.ms_channels}
  batch_size: ${model.train.batch_size}
  num_workers: ${model.train.num_workers}
  shuffle: True
validation:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.${dataset.name}.${dataset.name}
    root: ${oc.env:DATASET_PATH}/${dataset.name}
    fold: validation
    seed: 42
    output_size: 64
    channels: ${dataset.ms_channels}
  batch_size: ${model.train.batch_size}
  num_workers: ${model.train.num_workers}
  shuffle: False
test:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: dataset.${dataset.name}.${dataset.name}
    root: ${oc.env:DATASET_PATH}/${dataset.name}
    fold: test
    seed: 42
    output_size: 64
    channels: ${dataset.ms_channels}
  batch_size: ${model.train.batch_size}
  num_workers: ${model.train.num_workers}
  shuffle: False